const {test}=require('node:test'),assert=require('node:assert/strict');
const {EventEmitter}=require('node:events');
const {createAppUpdates,updateMode}=require('../electron/app-updates.cjs');
function fixture(options={}){const updater=new EventEmitter(),calls=[];updater.checkForUpdates=async()=>{calls.push('check');updater.emit('update-available',{version:'9.0.0'});return {};};updater.downloadUpdate=async()=>{calls.push('download');updater.emit('download-progress',{percent:50});updater.emit('update-downloaded',{version:'9.0.0'});};updater.quitAndInstall=()=>calls.push('install');const api=createAppUpdates({updater,packaged:true,platform:'win32',env:{},version:'1.0.0',openExternal:async()=>calls.push('release'),beforeInstall:async()=>calls.push('flush'),...options});return {api,calls,updater};}
test('automatic updates download and stage without interrupting work; explicit install saves first',async()=>{const f=fixture();await f.api.check();assert.deepEqual(f.calls,['check','download']);assert.equal(f.updater.autoInstallOnAppQuit,true);assert.equal(f.api.state().status,'downloaded');await f.api.install();assert.deepEqual(f.calls,['check','download','flush','install']);f.api.suspendInstall();assert.equal(f.updater.autoInstallOnAppQuit,false);});
test('busy tasks or save failure block installation; network errors do not quit',async()=>{const f=fixture({isBusy:()=>true});await f.api.check();await assert.rejects(f.api.install(),/任务/);assert.ok(!f.calls.includes('install'));const g=fixture({beforeInstall:async()=>{throw Error('save failed')}});await g.api.check();await assert.rejects(g.api.install(),/save failed/);assert.ok(!g.calls.includes('install'));const h=fixture();h.updater.checkForUpdates=async()=>{throw Error('offline')};await h.api.check();assert.equal(h.api.state().status,'error');assert.deepEqual(h.calls,[]);});
test('disabled updates and unsupported packages never silently download or install',async()=>{const f=fixture();await f.api.setEnabled(false);await f.api.check();assert.deepEqual(f.calls,['check']);assert.equal(f.updater.autoInstallOnAppQuit,false);for(const options of [{platform:'darwin',env:{}},{platform:'win32',env:{PORTABLE_EXECUTABLE_DIR:'C:/portable'}},{platform:'linux',env:{}}]){const g=fixture(options);await g.api.check();assert.deepEqual(g.calls,['check']);await assert.rejects(g.api.install(),/手动|发布页/);}assert.equal(updateMode({packaged:true,platform:'linux',env:{APPIMAGE:'/app'}}),'automatic');assert.equal(updateMode({packaged:false,platform:'win32',env:{}}),'development');});
test('concurrent update checks share one request and a preference failure leaves state intact',async()=>{let finish;const f=fixture();f.updater.checkForUpdates=()=>{f.calls.push('check');return new Promise(r=>finish=r);};const a=f.api.check(),b=f.api.check();finish({});await Promise.all([a,b]);assert.deepEqual(f.calls,['check']);const g=fixture({persist:async()=>{throw Error('disk')}});await assert.rejects(g.api.setEnabled(false),/disk/);assert.equal(g.api.state().enabled,true);});

test('reenabling a staged update registers install-on-quit through the cached download',async()=>{const f=fixture();await f.api.check();await f.api.setEnabled(false);assert.equal(f.updater.autoInstallOnAppQuit,false);await f.api.setEnabled(true);assert.equal(f.updater.autoInstallOnAppQuit,true);assert.deepEqual(f.calls,['check','download','download']);});
