'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const electronId=require.resolve('electron'),cached=require.cache[electronId];
const home=fs.mkdtempSync(path.join(fs.realpathSync.native(os.tmpdir()),'wickrun-butler-artifact-'));
require.cache[electronId]={id:electronId,filename:electronId,loaded:true,exports:{app:{getPath:()=>home}}};
const storeId=require.resolve('../electron/store.cjs'),storeCached=require.cache[storeId];
require.cache[storeId]={id:storeId,filename:storeId,loaded:true,exports:{kvGet:()=>null,secretGet:()=>null}};
const {runTool}=require('../electron/tools/index.cjs');
const {runtimeVersions}=require('../electron/code-versions.cjs');

test('automatic HTML and DOCX artifacts each have a verified revision that undoes creation',async t=>{
  t.after(()=>{if(cached)require.cache[electronId]=cached;else delete require.cache[electronId];
    if(storeCached)require.cache[storeId]=storeCached;else delete require.cache[storeId];
    assert.ok(path.resolve(home).startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(home,{recursive:true,force:true});});
  const root=path.join(home,'isolated');fs.mkdirSync(root);
  const output=path.join(root,'brief.html');
  const result=await runTool('write_document',{path:output,content:'# Reviewable draft\n\nA useful result.'},{workspaceRoots:[root],reviewCodeChanges:false});
  assert.equal(result.ok,true,result.error||result.content);
  assert.ok(fs.existsSync(output));
  assert.equal(result.codeChanges.length,1);
  assert.equal(result.codeChanges[0].kind,'added');
  const revisionId=result.codeChanges[0].revisionId;
  assert.ok(revisionId,result.codeChanges[0].revertUnavailable);
  const versions=runtimeVersions();
  versions.revert([revisionId],[root]);
  assert.equal(fs.existsSync(output),false);
  fs.writeFileSync(path.join(root,'unrelated-large.bin'),Buffer.alloc(17*1024*1024,4));
  const binary=path.join(root,'brief.docx');
  const document=await runTool('write_document',{path:binary,content:'# Reviewable draft'},{workspaceRoots:[root],reviewCodeChanges:false});
  assert.equal(document.ok,true,document.error||document.content);
  assert.ok(fs.existsSync(binary));
  assert.equal(document.codeChanges.length,1);
  assert.equal(document.codeChanges[0].binary,true);
  assert.ok(document.codeChanges[0].revisionId,document.codeChanges[0].revertUnavailable);
  versions.revert([document.codeChanges[0].revisionId],[root]);
  assert.equal(fs.existsSync(binary),false);
});
