const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createTeamFiles}=require('../electron/team-files.cjs');const {createConversationWorkspaces}=require('../electron/conversation-workspaces.cjs');
function fixture(t){const base=fs.realpathSync.native(os.tmpdir()),dir=fs.mkdtempSync(path.join(base,'wickrun-conversation-test-'));t.after(()=>{assert.equal(path.dirname(dir),base);assert.ok(path.basename(dir).startsWith('wickrun-conversation-test-'));fs.rmSync(dir,{recursive:true,force:true});});const root=path.join(dir,'project');fs.mkdirSync(root);fs.writeFileSync(path.join(root,'a.txt'),'baseline');const conversations=['a','b'].map(id=>({id,config:{toolsEnabled:true}})),settings={tools:{workspaceRoots:[root]}},teamFiles=createTeamFiles(path.join(dir,'data'));const api=createConversationWorkspaces({teamFiles,conversations:()=>conversations,settings:()=>settings});return {dir,root,conversations,settings,teamFiles,api};}
test('parallel Work forks do not share writes and conflicting merges cannot overwrite',t=>{const f=fixture(t);const a=f.api.create('a',f.root),b=f.api.create('b',f.root);assert.notEqual(a.isolatedRoot,b.isolatedRoot);f.conversations[0].workspace=a;f.conversations[1].workspace=b;
 fs.writeFileSync(path.join(a.isolatedRoot,'a.txt'),'task A');fs.writeFileSync(path.join(b.isolatedRoot,'a.txt'),'task B');assert.equal(fs.readFileSync(path.join(f.root,'a.txt'),'utf8'),'baseline');
 assert.deepEqual(f.api.create('a',f.root),a);const d=f.teamFiles.diff(a.id);f.teamFiles.merge(a.id,d.files.map(({path,beforeHash,afterHash})=>({path,beforeHash,afterHash})));assert.equal(f.teamFiles.diff(b.id).status,'conflict');assert.throws(()=>f.teamFiles.merge(b.id),/冲突|差异|核对|快照/);assert.equal(fs.readFileSync(path.join(f.root,'a.txt'),'utf8'),'task A');assert.throws(()=>f.api.resolve('a'),/不可用/);
});
test('workspace scope denies escalation, revoked roots, unrelated and forged sessions',t=>{const f=fixture(t),a=f.api.create('a',f.root);f.conversations[0].workspace=a;
 const ctx=f.api.tool({conversationId:'a',workspaceRoots:['/'],grants:{admin:true,extraRoots:['/']}});assert.deepEqual(ctx.workspaceRoots,[a.isolatedRoot]);assert.deepEqual(ctx.grants,{admin:false,screen:false,extraRoots:[]});
 assert.throws(()=>f.api.create('missing',f.root),/不存在/);assert.throws(()=>f.api.create('b',f.dir),/授权/);f.conversations[1].workspace=a;assert.throws(()=>f.api.resolve('b'),/不可用/);
 f.settings.tools.workspaceRoots=[];assert.throws(()=>f.api.resolve('a'),/撤销/);
});
