const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {createDurableJson}=require('../electron/durable-json.cjs');
const {createCollaborationStore}=require('../electron/collaboration-store.cjs');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'wickrun-storage-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return root;}
test('corruption and access failures never yield empty storage',t=>{const root=fixture(t),file=path.join(root,'store.json');fs.writeFileSync(file,'{partial');const d=createDurableJson(file,{initial:()=>({})});assert.throws(()=>d.read(),/读取失败/);assert.throws(()=>d.write({}),/读取失败/);assert.equal(fs.readFileSync(file,'utf8'),'{partial');const denied=createDurableJson(file,{initial:()=>({}),io:{...fs,readFileSync(){throw Object.assign(Error('denied'),{code:'EACCES'});}}});assert.throws(()=>denied.read(),/denied/);});
test('failed fsync leaves disk and memory unchanged; restart retains custom data',t=>{const root=fixture(t),file=path.join(root,'store.json');let fail=false;const io={...fs,fsyncSync(fd){if(fail)throw Object.assign(Error('full'),{code:'ENOSPC'});fs.fsyncSync(fd);}};const d=createDurableJson(file,{initial:()=>({rows:[]}),io});d.write({rows:['custom']});fail=true;assert.throws(()=>d.write({rows:[]}),/full/);assert.deepEqual(d.read().rows,['custom']);assert.deepEqual(createDurableJson(file,{initial:()=>({})}).read().rows,['custom']);});
test('atomic replacement retains last backup; missing primary fails safely',t=>{const root=fixture(t),file=path.join(root,'store.json'),d=createDurableJson(file,{initial:()=>({})});d.write({v:1});d.write({v:2});assert.equal(JSON.parse(fs.readFileSync(file+'.prev','utf8')).v,1);fs.unlinkSync(file);assert.throws(()=>createDurableJson(file,{initial:()=>({})}).read(),/已有备份/);});
test('failed atomic replacement keeps the primary present and recoverable',t=>{const root=fixture(t),file=path.join(root,'store.json');let fail=false;const io={...fs,renameSync(from,to){if(fail&&to===file){assert.equal(fs.existsSync(file),true);throw Error('replace failed');}return fs.renameSync(from,to);}};const d=createDurableJson(file,{initial:()=>({}),io});d.write({v:1});fail=true;assert.throws(()=>d.write({v:2}),/replace failed/);assert.equal(createDurableJson(file,{initial:()=>({})}).read().v,1);assert.equal(JSON.parse(fs.readFileSync(file+'.prev','utf8')).v,1);});
test('Windows transient rename failures retry backup and primary within one bounded budget',t=>{const root=fixture(t),file=path.join(root,'store.json'),sleeps=[];let armed=false;const failures=new Map([[file+'.prev',{remaining:1,code:'EBUSY'}],[file,{remaining:1,code:'EPERM'}]]);const io={...fs,renameSync(from,to){const failure=failures.get(to);if(armed&&failure&&failure.remaining>0){failure.remaining-=1;throw Object.assign(Error(failure.code),{code:failure.code});}return fs.renameSync(from,to);}};const d=createDurableJson(file,{initial:()=>({}),io,platform:'win32',sleep:ms=>sleeps.push(ms)});d.write({v:1});armed=true;d.write({v:2});assert.deepEqual(sleeps,[10,20]);assert.equal(sleeps.reduce((sum,ms)=>sum+ms,0)<=300,true);assert.equal(JSON.parse(fs.readFileSync(file,'utf8')).v,2);assert.equal(JSON.parse(fs.readFileSync(file+'.prev','utf8')).v,1);});
test('exhausted Windows rename retries preserve disk, cache and backup',t=>{const root=fixture(t),file=path.join(root,'store.json'),sleeps=[];let armed=false,attempts=0;const io={...fs,renameSync(from,to){if(armed&&to===file){attempts+=1;throw Object.assign(Error('locked'),{code:'EACCES'});}return fs.renameSync(from,to);}};const d=createDurableJson(file,{initial:()=>({}),io,platform:'win32',sleep:ms=>sleeps.push(ms)});d.write({v:1});armed=true;assert.throws(()=>d.write({v:2}),/locked/);assert.equal(attempts,6);assert.deepEqual(sleeps,[10,20,40,80,100]);assert.equal(sleeps.reduce((sum,ms)=>sum+ms,0),250);assert.equal(d.read().v,1);assert.equal(createDurableJson(file,{initial:()=>({})}).read().v,1);assert.equal(JSON.parse(fs.readFileSync(file+'.prev','utf8')).v,1);});
test('external primary change during a rename wait is never overwritten',t=>{const root=fixture(t),file=path.join(root,'store.json');let armed=false,attempts=0;const io={...fs,renameSync(from,to){if(armed&&to===file){attempts+=1;throw Object.assign(Error('busy'),{code:'EPERM'});}return fs.renameSync(from,to);}};const d=createDurableJson(file,{initial:()=>({}),io,platform:'win32',sleep(){fs.writeFileSync(file,JSON.stringify({v:'external'}));}});d.write({v:1});armed=true;assert.throws(()=>d.write({v:2}),/其他程序改动/);assert.equal(attempts,1);assert.equal(JSON.parse(fs.readFileSync(file,'utf8')).v,'external');assert.equal(d.read().v,'external');assert.equal(JSON.parse(fs.readFileSync(file+'.prev','utf8')).v,1);});
test('non-transient rename failures are not retried',t=>{const root=fixture(t),file=path.join(root,'store.json');let armed=false,attempts=0,sleeps=0;const io={...fs,renameSync(from,to){if(armed&&to===file){attempts+=1;throw Object.assign(Error('full'),{code:'ENOSPC'});}return fs.renameSync(from,to);}};const d=createDurableJson(file,{initial:()=>({}),io,platform:'win32',sleep(){sleeps+=1;}});d.write({v:1});armed=true;assert.throws(()=>d.write({v:2}),/full/);assert.equal(attempts,1);assert.equal(sleeps,0);assert.equal(d.read().v,1);assert.equal(createDurableJson(file,{initial:()=>({})}).read().v,1);assert.equal(JSON.parse(fs.readFileSync(file+'.prev','utf8')).v,1);});
function project(){return {id:'p',members:[],workflows:[],tasks:[],runs:[],memories:[],schedules:[],files:[],preferences:{mode:'team'},settings:{maxConcurrent:1}};}
test('stale writers are rejected, no events lost and versions cannot mutate',t=>{const d=createCollaborationStore(fixture(t));const p=project();d.update(0,p);p.members.push({id:'m',name:'custom'});d.update(1,p);assert.throws(()=>d.update(1,project()),/已有更新/);assert.equal(d.read().projects.p.members[0].name,'custom');p.workflows.push({id:'f',versions:[{id:'v',graph:{x:4}}]});d.update(2,p);p.workflows[0].versions[0].graph.x=0;assert.throws(()=>d.update(3,p),/不可改写/);});
test('claim is unique and crash marks attempts uncertain without auto execution',t=>{const root=fixture(t),d=createCollaborationStore(root);require('./team-store-fixtures.cjs').install(d,root);d.claim('p','r');const data=d.read(),p=data.projects.p;p.runs[0].attempts.push({id:'a',nodeId:'node',status:'running'});d.update(data.revision,p);assert.throws(()=>d.claim('p','r'),/尚未就绪/);const next=createCollaborationStore(root).read().projects.p.runs[0];assert.equal(next.status,'uncertain');assert.equal(next.attempts[0].status,'uncertain');});
