const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {loader}=require('./load-ts.cjs');const {createCollaborationStore}=require('../electron/collaboration-store.cjs');
function fixture(t,execute){const root=fs.mkdtempSync(path.join(os.tmpdir(),'wickrun-team-runtime-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const store=createCollaborationStore(root),calls=[];
 const bridge={collaborationRead:async()=>store.read(),collaborationUpdate:async(rev,p)=>store.update(rev,p),collaborationClaim:async(p,id)=>store.claim(p,id),toolAbort:async()=>{}};
 const load=loader({'./store':{uid:()=>crypto.randomUUID(),secretGet:async()=> 'fake-local-fixture-key',toolContextOf:()=>({grants:{extraRoots:[],screen:false,admin:false}})},'./transport':{desktop:()=>bridge},'./agent':{runAgent(args){calls.push(args);let aborted=false;queueMicrotask(()=>void (async()=>{try{await execute(args,()=>aborted);}catch(e){args.events.onError(e.message,{kind:'unknown'});}})());return {abort(){aborted=true;args.events.onPaused?.('cancelled');}};}}});
 const {TeamRuntime,nextTeamTrigger}=load(path.resolve('src/lib/team-runtime.ts')),domain=load(path.resolve('src/lib/collaboration.ts')),runtime=new TeamRuntime();
 const cfg=load(path.resolve('src/lib/paramSchema.ts')).defaultGenerationConfig();const settings={defaultConfig:cfg,keyProfiles:[{id:'key',name:'Fixture',baseUrl:'https://example.invalid'}],effortMappings:[],requestTimeoutMs:1000,autoRetry:0};runtime.settings=()=>settings;
 return {root,store,runtime,calls,cfg,domain,nextTeamTrigger};
}
async function setup(f,{parallel=false,configure,scheduleKey}={}){await f.runtime.load();const p=f.domain.emptyTeamProject('p');p.settings.maxConcurrent=parallel?2:1;p.members=[{id:'a',name:'A',instructions:'role',connectionId:'key',model:'fixture',effort:'medium',enabled:true,tools:[],maxTokens:4000,maxMinutes:1}];const flow=f.domain.newWorkflow('Flow'),s=flow.draft.nodes[0],e=flow.draft.nodes[1],a=f.domain.newNode('agent');a.memberId='a';a.instructions='do work';a.outputRequirement='real evidence';e.outputRequirement='review result';let nodes=[s,a,e],pairs=[[s,a],[a,e]];
 if(parallel){const b={...structuredClone(a),id:'b'},fork=f.domain.newNode('parallel'),join=f.domain.newNode('join');nodes=[s,fork,a,b,join,e];pairs=[[s,fork],[fork,a],[fork,b],[a,join],[b,join],[join,e]];}
 flow.draft.nodes=nodes;flow.draft.edges=pairs.map(([from,to])=>({id:crypto.randomUUID(),from:from.id,to:to.id,port:'next',label:'next',maxTraversals:5}));flow.draft.maxTokens=10000;flow.versions=[{id:'v',number:1,createdAt:1,graph:structuredClone(flow.draft)}];p.workflows=[flow];p.tasks=[{id:'task',title:'Fixture',goal:'Goal',acceptance:'Evidence',entries:[],status:'ready',createdAt:1}];configure?.(p,flow);await f.runtime.update('p',target=>Object.assign(target,p));const id=await f.runtime.createRun('p','task',flow.id,'v',f.cfg,scheduleKey);return {id,flow,p};}
test('actual workflow dispatch persists attempt before call and needs user delivery acceptance',async t=>{let f;f=fixture(t,async args=>{const disk=f.store.read().projects.p.runs[0];assert.ok(disk.attempts.some(a=>a.status==='running'));args.events.onContentDelta('verified result');await args.events.onRunState({working:[],round:1,at:1,stoppedBy:'unknown',status:'completed',spentTokens:317});args.events.onDone();});const {id}=await setup(f);await f.runtime.start('p',id);let r=f.runtime.project('p').runs[0];assert.equal(r.status,'waiting_user');assert.equal(r.tokens,317);assert.equal(f.calls.length,1);await f.runtime.approve('p',id,true);r=f.runtime.project('p').runs[0];assert.equal(r.status,'completed');assert.equal(f.runtime.project('p').tasks[0].status,'已完成');});
test('parallel branches reserve bounded capacity and join before delivery',async t=>{let f;const reservations=[];f=fixture(t,async args=>{reservations.push(f.store.read().projects.p.runs[0].reservations);await new Promise(resolve=>setTimeout(resolve,10));args.events.onContentDelta('evidence');args.events.onUsage({total_tokens:150});await args.events.onRunState({working:[],round:1,at:1,stoppedBy:'unknown',status:'completed',spentTokens:180});args.events.onDone();});const {id}=await setup(f,{parallel:true});await f.runtime.start('p',id);const r=f.runtime.project('p').runs[0];assert.equal(f.calls.length,2);assert.equal(r.status,'waiting_user');assert.equal(r.tokens,360);assert.deepEqual(r.reservations,{});assert.ok(reservations.every(map=>Object.values(map).reduce((sum,n)=>sum+n,0)<=10000));assert.equal(r.attempts.filter(a=>a.nodeId===r.version.graph.nodes.find(n=>n.type==='join').id).length,1);});
test('failed attempt remains in history and repeated explicit retry can be resolved',async t=>{const f=fixture(t,async args=>args.events.onError('fixture failure',{kind:'auth'}));const {id}=await setup(f);await f.runtime.start('p',id);assert.equal(f.runtime.project('p').runs[0].status,'uncertain');await f.runtime.resolveUncertain('p',id,'retry','verified no external side effect');await f.runtime.start('p',id);assert.equal(f.calls.length,2);await f.runtime.resolveUncertain('p',id,'retry','checked second failure');assert.equal(f.runtime.project('p').runs[0].status,'paused');assert.equal(f.runtime.project('p').runs[0].attempts.filter(a=>a.status==='failed').length,2);});
test('graph accepts bounded cycles with exit and rejects missing members and unbounded rules',t=>{const f=fixture(t,async()=>{}),{newWorkflow,newNode,validateGraph}=f.domain,flow=newWorkflow(),s=flow.draft.nodes[0],e=flow.draft.nodes[1],c=newNode('condition');e.outputRequirement='final';c.condition={source:s.id,contains:'done'};flow.draft.nodes=[s,c,e];flow.draft.edges=[{id:'a',from:s.id,to:c.id,label:'go',maxTraversals:5},{id:'b',from:c.id,to:s.id,port:'fail',label:'loop',loop:true,maxTraversals:4},{id:'c',from:c.id,to:e.id,port:'pass',label:'exit',maxTraversals:5},{id:'d',from:c.id,to:e.id,port:'default',label:'other',maxTraversals:5}];assert.deepEqual(validateGraph(flow.draft,[]),[]);flow.draft.edges[1].maxTraversals=0;assert.ok(validateGraph(flow.draft,[]).some(i=>/回路.*次数上限/.test(i.message)));});
test('explicit timezone daily trigger crosses DST without local-machine dependence',t=>{const f=fixture(t,async()=>{});const next=f.nextTeamTrigger('America/Vancouver',9,0,Date.parse('2026-03-07T18:00:00Z'));assert.equal(new Date(next).toISOString(),'2026-03-08T16:00:00.000Z');assert.throws(()=>f.nextTeamTrigger('invalid/zone',9,0),/time zone/i);});

test('explicit retry resumes stored member checkpoint without charging prior usage twice',async t=>{let f;f=fixture(t,async args=>{if(f.calls.length===1){args.events.onContentDelta('partial');await args.events.onRunState({working:[],round:2,at:1,stoppedBy:'unknown',status:'paused',content:'partial',spentTokens:100});args.events.onError('interrupted',{kind:'unknown'});}else{assert.equal(args.resume.content,'partial');assert.equal(args.resolveUncertain,'retry');args.events.onContentDelta(' verified');await args.events.onRunState({...args.resume,status:'completed',spentTokens:140});args.events.onDone();}});const {id}=await setup(f);await f.runtime.start('p',id);await f.runtime.resolveUncertain('p',id,'retry','verified external action');await f.runtime.start('p',id);assert.equal(f.runtime.project('p').runs[0].tokens,140);assert.equal(f.runtime.project('p').runs[0].status,'waiting_user');});
test('multiple delivery endpoints can each be accepted with concurrency one',async t=>{const f=fixture(t,async args=>{args.events.onContentDelta('actual result');args.events.onDone();});const {id}=await setup(f,{configure(p,flow){const end=flow.draft.nodes.at(-1),second={...end,id:'second-end'};flow.draft.nodes.push(second);flow.draft.edges.push({...flow.draft.edges.at(-1),id:'second-edge',to:second.id});flow.versions[0].graph=structuredClone(flow.draft);}});await f.runtime.start('p',id);assert.equal(f.runtime.project('p').runs[0].approvalQueue.length,2);await f.runtime.approve('p',id,true);assert.equal(f.runtime.project('p').runs[0].status,'waiting_user');await f.runtime.approve('p',id,true);assert.equal(f.runtime.project('p').runs[0].status,'completed');});
test('discussion retry keeps completed participant results',async t=>{let f;f=fixture(t,async args=>{const isB=args.extraSystem.includes('成员 B');if(isB&&f.calls.length===2){await args.events.onRunState({working:[],round:1,at:1,spentTokens:90,status:'paused',content:'B partial'});args.events.onError('interrupt B',{kind:'unknown'});}else{if(isB)assert.equal(args.resume.content,'B partial');args.events.onContentDelta(isB?'B final':'A final');args.events.onDone();}});const {id}=await setup(f,{configure(p,flow){p.members.push({...p.members[0],id:'b',name:'B'});const a=flow.draft.nodes.find(n=>n.type==='agent');a.type='discussion';a.participants=['a','b'];flow.versions[0].graph=structuredClone(flow.draft);}});await f.runtime.start('p',id);await f.runtime.resolveUncertain('p',id,'retry','B has no completed external action');await f.runtime.start('p',id);assert.equal(f.calls.length,3);assert.equal(f.runtime.project('p').runs[0].status,'waiting_user');assert.match(f.runtime.project('p').runs[0].attempts.at(-2).output,/A final/);});
test('bound scheduled ready run is recovered once after interruption before dispatch',async t=>{const f=fixture(t,async args=>{args.events.onContentDelta('scheduled evidence');args.events.onDone();});const key='schedule:2026-09-13';const {id}=await setup(f,{scheduleKey:key});await f.runtime.update('p',p=>p.schedules.push({id:'schedule',name:'Scheduled',workflowId:p.workflows[0].id,versionId:'v',goal:'Goal',acceptance:'Evidence',timezone:'UTC',hour:9,minute:0,catchUp:true,overlap:'skip',enabled:true,nextAt:Date.now()+86400000,triggers:[{key,at:Date.now()-1000,runId:id}]}));await f.runtime.tick();for(let i=0;i<100&&f.runtime.project('p').runs[0].status!=='waiting_user';i++)await new Promise(r=>setTimeout(r,5));await f.runtime.tick();assert.equal(f.runtime.project('p').runs.length,1);assert.equal(f.calls.length,1);assert.equal(f.runtime.project('p').runs[0].status,'waiting_user');});
