import { localizeRoles } from '../lib/role-locale';
import { useT, useLocale } from '../lib/i18n';
import React from 'react';
import type { AppSettings, GenerationConfig } from '../types';
import { filterRoles, libraryRoles } from '../lib/office-library';
import { teamRuntime } from '../lib/team-runtime';
import AgentAvatar from './AgentAvatar';
import './collaboration/AgentOffice.css';
export default function AgentRolePicker({settings,config,profileId,onConfig,value,projectId,onChange,onBrain}:{settings:AppSettings;config:GenerationConfig;profileId?:string;onConfig:(patch:Partial<GenerationConfig>)=>void;value:GenerationConfig['agentRole'];projectId?:string|null;onChange:(role:GenerationConfig['agentRole'])=>void;onBrain:(profileId:string,model:string)=>void}){
  const tx=useT(),locale=useLocale();
  const [open,setOpen]=React.useState(false);const [query,setQuery]=React.useState('');const [category,setCategory]=React.useState('');const [limit,setLimit]=React.useState(30);const [chosen,setChosen]=React.useState<string[]>([]);
  const anchor=React.useRef<HTMLDetailsElement>(null);const [menuStyle,setMenuStyle]=React.useState<React.CSSProperties>({});
  React.useLayoutEffect(()=>{if(!open)return;const place=()=>{const rect=anchor.current?.getBoundingClientRect();if(!rect)return;const width=Math.min(340,window.innerWidth-24);const above=rect.top-12;const below=window.innerHeight-rect.bottom-12;const upward=above>=below;setMenuStyle({position:'fixed',width,left:Math.max(12,Math.min(rect.right-width,window.innerWidth-width-12)),right:'auto',bottom:upward?window.innerHeight-rect.top+6:'auto',top:upward?'auto':rect.bottom+6,maxHeight:Math.max(120,Math.min(340,(upward?above:below)-6))});};place();window.addEventListener('resize',place);window.addEventListener('scroll',place,true);return()=>{window.removeEventListener('resize',place);window.removeEventListener('scroll',place,true);};},[open]);
  const project=projectId?teamRuntime.project(projectId):undefined;const members=(project?.members??[]).filter(m=>m.enabled&&!m.connectionId.startsWith('client:'));
  const roles=localizeRoles(libraryRoles(settings.officeLibrary,project?.office?.customRoles),locale);const results=filterRoles(roles,query,category);
  const toggle=(id:string)=>setChosen(chosen.includes(id)?chosen.filter(x=>x!==id):chosen.length<8?[...chosen,id]:chosen);
  function activate(){if(!profileId||!config.model||!chosen.length)return;const workers=chosen.map(id=>{const member=members.find(m=>m.id===id);const role=member??roles.find(r=>r.id===id)!;return {id:'role-'+id,label:role.name,profileId:member?.connectionId||profileId!,model:member?.model||config.model,role:{id:role.id,name:role.name,instructions:role.instructions}};});onConfig({subagents:{enabled:true,workers,maxCalls:Math.max(4,workers.length),allowEdits:false}});setOpen(false);}
  return <details ref={anchor} className="agent-role-picker" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>{config.subagents?.enabled&&config.subagents.workers.some(w=>w.role)?tx("角色协作 · {p0}",{p0:config.subagents.workers.filter(w=>w.role).length}):value?tx("职责 · {p0}",{p0:value.name}):tx("调用角色")}</summary><div className="agent-role-menu" style={menuStyle}><p>{tx("勾选角色启用协作；点击名称设置主模型职责。")}</p>
    <div className="role-search-fields"><label className="team-field"><span>{tx("搜索角色")}</span><input aria-label={tx("对话角色搜索")} value={query} onChange={e=>{setQuery(e.target.value);setLimit(30);}}/></label><label className="team-field"><span>{tx("分类")}</span><select aria-label={tx("对话角色分类")} value={category} onChange={e=>{setCategory(e.target.value);setLimit(30);}}><option value="">{tx("全部分类")}</option>{[...new Set(roles.map(r=>r.division))].map(c=><option key={c} value={c}>{tx(c)}</option>)}</select></label></div>
    <div className="office-batch-actions"><button type="button" className="btn sm" disabled={!chosen.length||!profileId||!!config.client} onClick={activate}>{tx("启用角色协作（{count} / 8）",{count:chosen.length})}</button>{config.subagents?.enabled&&<button type="button" className="btn sm" onClick={()=>onConfig({subagents:{...config.subagents!,enabled:false}})}>{tx("停用临时协作")}</button>}{value&&<button type="button" className="btn sm" onClick={()=>{onChange(undefined);setOpen(false);}}>{tx("移除主模型职责")}</button>}</div>
    {config.subagents?.enabled&&<details className="role-enabled-summary"><summary>{tx("已启用 {count} 个工作角色 · 查看名单",{count:config.subagents.workers.length})}</summary><p>{config.subagents.workers.map(w=>w.role?.name??w.label??w.model).join('、')}{tx("。最多同时运行两个子代理。")}</p></details>}
    {config.client&&<p>{tx("当前连接为外部客户端；这里的独立子代理执行需要切换到 API 模型。外部客户端可使用自己的协作能力。")}</p>}
    {members.filter(m=>!category&&`${m.name} ${m.model}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(m=><div className="office-role-tile" key={m.id}><input type="checkbox" aria-label={tx("协作角色 {p0}",{p0:m.name})} checked={chosen.includes(m.id)} disabled={!chosen.includes(m.id)&&chosen.length>=8} onChange={()=>toggle(m.id)}/><button type="button" className="office-role-option" onClick={()=>{onChange({id:m.id,name:m.name,instructions:m.instructions});onBrain(m.connectionId,m.model);setOpen(false);}}><AgentAvatar name={m.name} seed={m.roleTemplateId??m.id}/><span>{m.name}<small>{tx("办公室 ·")}{m.model||tx("待配置模型")}</small></span></button></div>)}
    {results.slice(0,limit).map(r=><div className="office-role-tile" key={r.id}><input type="checkbox" aria-label={tx("协作角色 {p0}",{p0:r.name})} checked={chosen.includes(r.id)} disabled={!chosen.includes(r.id)&&chosen.length>=8} onChange={()=>toggle(r.id)}/><button type="button" className="office-role-option" onClick={()=>{onChange({id:r.id,name:r.name,instructions:r.instructions});setOpen(false);}}><AgentAvatar name={r.name} color={r.color} seed={r.id}/><span>{r.name}<small>{tx(r.division)} · {r.summary}</small></span></button></div>)}
    {!results.length&&<p>{tx("没有找到匹配角色。")}</p>}{results.length>limit&&<button type="button" className="btn sm" onClick={()=>setLimit(limit+30)}>{tx("显示更多（{count} / {total}）",{count:limit,total:results.length})}</button>}
  </div></details>;
}
