import { localizeRoles } from '../../lib/role-locale';
import { useT, useLocale } from '../../lib/i18n';
import React from 'react';
import type { AppSettings } from '../../types';
import type { TeamProject, Member } from '../../lib/collaboration';
import { ensureOffice, officeOf, addRole, moveDepartment, moveMember, dissolveDepartment, mergeDepartment, captureModule, installModule, descendants, type AgentRole } from '../../lib/office';
import { uid } from '../../lib/store';
import { desktop } from '../../lib/transport';
import OfficePlanner from './OfficePlanner';
import AgentAvatar from '../AgentAvatar';
import Markdown from '../Markdown';
import './AgentOffice.css';
import OfficeLibrary from './OfficeLibrary';
import { libraryRoles, saveDepartment } from '../../lib/office-library';
const DRAG='application/x-wickrun-office';
export default function AgentOffice({project,settings,update,onMember,onWorkflow,onTask,onSettings,onSettingsChange,memoryItems,onMemory}:{project:TeamProject;settings:AppSettings;update:(fn:(p:TeamProject)=>void)=>Promise<unknown>;onMember:(member:Member)=>void;onWorkflow:(id:string)=>void;onTask:(id:string)=>void;onSettings:()=>void;onSettingsChange?:(fn:(s:AppSettings)=>AppSettings)=>void;memoryItems?:import('../../lib/memory-core').ProjectMemoryItem[];onMemory?:(fn:(items:import('../../lib/memory-core').ProjectMemoryItem[])=>import('../../lib/memory-core').ProjectMemoryItem[])=>void}){
  const tx=useT(),locale=useLocale();
  const o=officeOf(project),[selected,setSelected]=React.useState(''),[roleId,setRoleId]=React.useState(''),[detailsOpen,setDetailsOpen]=React.useState(false),[error,setError]=React.useState(''),[notice,setNotice]=React.useState(''),[hover,setHover]=React.useState('');
  const roles=localizeRoles(libraryRoles(settings.officeLibrary,o.customRoles),locale),role=roles.find(r=>r.id===roleId),active=o.departments.find(d=>d.id===selected)??o.departments[0];
  const inspector=React.useRef<HTMLElement>(null);const [inspectorHeight,setInspectorHeight]=React.useState<number>();
  React.useLayoutEffect(()=>{if(!detailsOpen||!role)return;const fit=()=>{const top=inspector.current?.getBoundingClientRect().top;if(top!==undefined)setInspectorHeight(Math.max(240,window.innerHeight-Math.max(64,top)-24));};fit();window.addEventListener('resize',fit);return()=>{window.removeEventListener('resize',fit);};},[detailsOpen,roleId]);
  const act=(fn:(p:TeamProject)=>void,success=tx("已保存"))=>{setError('');void update(fn).then(()=>setNotice(success)).catch(e=>setError(String(e)));};
  const brain={profileId:settings.activeKeyProfileId??settings.keyProfiles[0]?.id??'',model:settings.defaultConfig.model};
  const add=(r:AgentRole,departmentId=active?.id)=>{if(!departmentId){setError(tx("先新建一个部门，或让协作设计助手帮你组队。"));return;}act(p=>{addRole(p,departmentId,r,brain);},tx("{p0} 已加入部门，可单独配置模型和职责",{p0:r.name}));};
  const drag=(e:React.DragEvent,kind:string,id:string)=>{e.stopPropagation();e.dataTransfer.setData(DRAG,JSON.stringify({kind,id}));e.dataTransfer.effectAllowed=kind==='role'?'copy':'move';};
  const drop=(e:React.DragEvent,id?:string)=>{e.preventDefault();e.stopPropagation();setHover('');try{const data=JSON.parse(e.dataTransfer.getData(DRAG));if(data.kind==='department')act(p=>moveDepartment(ensureOffice(p),data.id,id));else if(id&&data.kind==='member')act(p=>moveMember(p,data.id,id));else if(id&&data.kind==='role'){const r=roles.find(r=>r.id===data.id);if(r)add(r,id);}}catch{setError(tx("没有识别到可放置的角色或部门"));}};
  const createDepartment=(name:string)=>{const id=uid('dept');act(p=>{ensureOffice(p).departments.push({id,name,purpose:'',memberIds:[],workflowIds:[]});});setSelected(id);};
  const renderDepartment=(id:string,depth=0):React.ReactNode=>{const d=o.departments.find(d=>d.id===id);if(!d||depth>30)return null;const child=o.departments.filter(c=>c.parentId===d.id);return <section key={id} className={`office-department${active?.id===id?' selected':''}${hover===id?' drop-target':''}`} aria-label={tx("部门 {p0}",{p0:d.name})} onDragOver={e=>{e.preventDefault();e.stopPropagation();setHover(id);}} onDragLeave={()=>setHover('')} onDrop={e=>drop(e,id)}>
    <header draggable onDragStart={e=>drag(e,'department',id)}><button className="office-department-name" onClick={()=>setSelected(id)} aria-pressed={active?.id===id}>{d.name}</button><span>{d.memberIds.length} {tx("位成员")}{child.length?tx(" · {p0} 个子部门",{p0:child.length}):''}</span><button className="btn sm ghost" onClick={()=>{setSelected(id);document.getElementById('office-department-settings')?.scrollIntoView({block:'nearest'});}}>{tx("整理")}</button></header>
    {d.purpose&&<p>{d.purpose}</p>}
    <div className="office-desks">{d.memberIds.map(mid=>{const m=project.members.find(m=>m.id===mid);if(!m)return null;const template=roles.find(r=>r.id===m.roleTemplateId);return <article className="office-desk" key={mid} draggable onDragStart={e=>drag(e,'member',mid)}><button className="office-person" onClick={()=>onMember(structuredClone(m))}><AgentAvatar name={m.name} color={template?.color} seed={m.roleTemplateId??mid}/><strong>{m.name}</strong><small>{m.enabled?(m.model||tx("选择模型大脑")):tx("已停用")}</small></button><select aria-label={tx("移动{p0}到部门",{p0:m.name})} value={id} onChange={e=>act(p=>moveMember(p,mid,e.target.value))}>{o.departments.map(target=><option key={target.id} value={target.id}>{target.name}</option>)}</select></article>;})}
      {!d.memberIds.length&&<button className="office-empty-desk" onClick={()=>setSelected(id)}>{tx("将角色拖到这里")}<br/><small>{tx("或选中此部门，再点击角色的“加入”")}</small></button>}
    </div>
    {d.workflowIds.length>0&&<div className="office-flow-links">{d.workflowIds.map(fid=>{const f=project.workflows.find(f=>f.id===fid);return f?<button key={fid} className="btn sm" onClick={()=>onWorkflow(fid)}>{tx("查看流程 ·")}{f.name}</button>:null;})}</div>}
    {!!child.length&&<div className="office-children">{child.map(c=>renderDepartment(c.id,depth+1))}</div>}
  </section>;};
  return <div className="agent-office">
    <details className="office-assistant-entry"><summary>{tx("需要帮你设计团队？找管家一起商量")}</summary><OfficePlanner onSettingsChange={onSettingsChange} memoryItems={memoryItems} onMemory={onMemory} key={project.id} project={project} settings={settings} update={update} onTask={onTask} onSettings={onSettings}/></details>
    <div className="office-heading"><div><h2>{tx("你的办公室")}</h2><p>{tx("角色是职责模板，放进部门后成为独立成员。这里组队，任务页开始工作。")}</p></div><form className="office-create" onSubmit={e=>{e.preventDefault();const form=e.currentTarget,name=new FormData(form).get('name')?.toString().trim();if(name){createDepartment(name);form.reset();}}}><input name="name" aria-label={tx("新部门名称")} placeholder={tx("新部门名称")} required maxLength={80}/><button className="btn">{tx("新建部门")}</button></form></div>
    {role&&!detailsOpen&&<button id="office-role-reopen" type="button" className="btn sm office-role-reopen" aria-expanded={false} aria-controls="office-role-inspector" onClick={()=>setDetailsOpen(true)}>{tx('展开角色说明：{name}',{name:role.name})}</button>}
    <div aria-live="polite" className="office-notice">{notice}</div>{error&&<p className="team-error" role="alert">{error}</p>}
    <div className={`office-layout${role&&detailsOpen?' with-inspector':''}`}><OfficeLibrary project={project} settings={settings} onSettings={onSettingsChange} activeId={active?.id} selectedRoleId={roleId} onRole={id=>{setRoleId(id);setDetailsOpen(true);}} onSelected={setSelected} onDrag={(e,r)=>drag(e,'role',r.id)} act={act} onNotice={setNotice} onError={setError}/>
    {role&&detailsOpen&&<aside ref={inspector} style={{maxHeight:inspectorHeight}} className="office-role-details" id="office-role-inspector" aria-label={tx('角色说明')}><header><h3>{role.name}</h3><button className="btn sm" type="button" aria-expanded={true} aria-controls="office-role-inspector" onClick={()=>{setDetailsOpen(false);requestAnimationFrame(()=>document.getElementById('office-role-reopen')?.focus());}}>{tx('收合说明')}</button></header><div className="office-role-detail-body"><small>{tx('来源简介（原文）')}</small><p>{role.summary}</p>{role.source?.startsWith('https://github.com/')?<a href={role.source} target="_blank" rel="noreferrer">{tx('查看固定版本的角色来源')}</a>:<small>{role.source}</small>}<details open><summary>{tx('原始角色 Prompt · 加入后可独立修改')}</summary><Markdown text={role.instructions}/></details></div></aside>}
    <div className="office-floor"><div className={`office-root-drop${hover==='root'?' drop-target':''}`} onDragOver={e=>{e.preventDefault();setHover('root');}} onDrop={e=>drop(e)}>{tx("独立部门 · 拖到这里移出上级部门")}</div>{o.departments.filter(d=>!d.parentId).map(d=>renderDepartment(d.id))}{!o.departments.length&&<div className="office-welcome"><h3>{tx("从一个想法开始，也可以先组队")}</h3><p>{tx("上方助手可以替你拟定分工；已有明确安排时，新建部门并把角色放进来。")}</p></div>}
    {active&&<details className="office-department-settings" id="office-department-settings" key={active.id}><summary>{tx("整理“")}{active.name}{tx("” · 层级、分工与复用")}</summary><div className="team-form-grid"><label className="team-field"><span>{tx("部门名称")}</span><input value={active.name} maxLength={80} onChange={e=>{const value=e.target.value;act(p=>{ensureOffice(p).departments.find(d=>d.id===active.id)!.name=value;});}}/></label><label className="team-field"><span>{tx("上级部门")}</span><select aria-label={tx("上级部门")} value={active.parentId??''} onChange={e=>{const parent=e.target.value;act(p=>moveDepartment(ensureOffice(p),active.id,parent||undefined));}}><option value="">{tx("独立部门")}</option>{o.departments.filter(d=>!descendants(o,active.id).some(c=>c.id===d.id)).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div><label className="team-field"><span>{tx("这个部门负责什么")}</span><textarea value={active.purpose} rows={2} onChange={e=>{const value=e.target.value;act(p=>{ensureOffice(p).departments.find(d=>d.id===active.id)!.purpose=value;});}}/></label>
    <div className="team-actions"><button className="btn" onClick={()=>act(p=>{installModule(p,captureModule(p,active.id),active.parentId);},tx("已复制整组部门、成员与流程草案，配置相互独立"))}>{tx("复制整组")}</button><button className="btn" onClick={()=>act(p=>{ensureOffice(p).modules.push(captureModule(p,active.id));},tx("已保存部门模块，可再次组装"))}>{tx("存为部门模块")}</button><button className="btn" disabled={!onSettingsChange} onClick={()=>{try{const module=captureModule(project,active.id);const next=saveDepartment(settings.officeLibrary??{},module);onSettingsChange?.(s=>({...s,officeLibrary:next}));setNotice(tx("已保存到我的部门库，所有项目可复用"));}catch(e){setError(String(e));}}}>{tx("保存到我的部门库")}</button><button className="btn" onClick={()=>{const module=captureModule(project,active.id);module.members=module.members.map(m=>({...m,connectionId:'',model:'',tools:[],skills:[],failover:undefined}));void desktop()!.saveArtifact(`${active.name.replace(/[^\p{L}\p{N}_-]/gu,'_')}-department.json`,JSON.stringify({format:'wickrun-department-v1',module},null,2)).catch(e=>setError(String(e)));}}>{tx("导出模块")}</button><button className="btn" onClick={()=>act(p=>dissolveDepartment(p,active.id),tx("已拆散部门，成员与已有流程仍保留；没有上级的成员可在下方重新分配"))}>{tx("拆散部门")}</button></div>
    <label className="team-field"><span>{tx("合并到其他部门（成员、子部门和流程一起移动）")}</span><select value="" onChange={e=>{const target=e.target.value;if(target)act(p=>mergeDepartment(p,active.id,target));}}><option value="">{tx("选择合并目标")}</option>{o.departments.filter(d=>!descendants(o,active.id).some(c=>c.id===d.id)).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>
    <label className="team-field"><span>{tx("关联已有流程（不改变执行规则）")}</span><select value="" onChange={e=>{const id=e.target.value;if(id)act(p=>{const d=ensureOffice(p).departments.find(d=>d.id===active.id)!;if(!d.workflowIds.includes(id))d.workflowIds.push(id);});}}><option value="">{tx("选择流程")}</option>{project.workflows.filter(f=>!f.archived&&!active.workflowIds.includes(f.id)).map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label></details>}
    {project.members.some(m=>!o.departments.some(d=>d.memberIds.includes(m.id)))&&<details><summary>{tx("待分配的已有成员")}</summary>{project.members.filter(m=>!o.departments.some(d=>d.memberIds.includes(m.id))).map(m=><div className="team-row" key={m.id}><span>{m.name}</span><button className="btn sm" disabled={!active} onClick={()=>act(p=>moveMember(p,m.id,active!.id))}>{tx("加入")}{active?.name}</button></div>)}</details>}
    </div></div>

  </div>;
}
