import React from 'react';
import { useT } from '../../lib/i18n';
import {desktop} from '../../lib/transport';
import {Modal} from '../ui';
export default function DataBackupPanel({beforeRestore}:{beforeRestore?:()=>Promise<void>}){
 const t = useT();
 const [status,setStatus]=React.useState<Record<string,unknown>|null>(null),[list,setList]=React.useState<Record<string,unknown>[]>([]),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false);
 const [preview,setPreview]=React.useState<{input:{id?:string;token?:string};summary:Record<string,unknown>}|null>(null);
 const load=async()=>{const bridge=desktop();if(!bridge)return;const [status,list]=await Promise.all([bridge.backupStatus(),bridge.backupList()]);setStatus(status);setList(list);};
 React.useEffect(()=>{void load().catch(e=>setError(String(e)));},[]);
 const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await load();}catch(e){setError(String(e));}finally{setBusy(false);}};
 return <div className="team-backup"><p>{t('备份包含本机配置、会话内联附件、协作空间、运行检查点和托管隔离文件。外部目录中的原始文件不包含在内。')}</p>{status&&<p style={{overflowWrap:'anywhere'}}>{t('数据位置：')}{String(status.storePath??t('未知'))}</p>}<div className="team-actions"><button className="btn" disabled={busy} onClick={()=>void act(()=>desktop()!.backupCreate('local'))}>{t('创建本机备份')}</button><button className="btn" disabled={busy} onClick={()=>void act(()=>desktop()!.backupCreate('export'))}>{t('导出完整归档')}</button><button className="btn" disabled={busy} onClick={()=>void act(()=>desktop()!.backupPreview().then(setPreview))}>{t('从文件恢复…')}</button></div><p className="team-note">{t('导出归档不包含 API Key 与远程连接令牌。本机备份保留可用的加密凭据；跨设备恢复后可能需要重新登录。备份不会自动过期删除。')}</p>{error&&<p role="alert">{error}</p>}{list.length>0&&<details><summary>已有备份（{list.length}）</summary>{list.map(item=><div className="team-row" key={String(item.id)}><span>{String(item.createdAt??item.id)}<small>{item.recoveryOnly?'恢复前保留的原文件':`${Number(item.fileCount??0)} 个文件 · ${Math.round(Number(item.totalBytes??0)/1024)} KB`}</small></span>{!item.recoveryOnly&&<button className="btn sm" disabled={busy||item.verified===false} onClick={()=>void act(()=>desktop()!.backupPreview(String(item.id)).then(setPreview))}>{t('预览恢复')}</button>}</div>)}</details>}{preview&&<Modal title={t('确认恢复范围')} onClose={()=>setPreview(null)} footer={<button className="btn primary" disabled={busy} onClick={()=>void act(async()=>{await beforeRestore?.();await desktop()!.backupRestore(preview.input);})}>{t('暂停运行、恢复并重启')}</button>}><p>{t('此备份会替换应用的本地配置与记录。恢复前会保留当前文件；恢复失败时回滚。外部项目原文件不受此操作影响。')}</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(preview.summary,null,2)}</pre>{error&&<p role="alert">{error}</p>}</Modal>}</div>;
}
