import React from 'react';
import { useT } from '../../lib/i18n';
import type {AppSettings} from '../../types';
import {desktop} from '../../lib/transport';
export default function LocalClientsPanel({settings,onChange}:{settings:AppSettings;onChange:(patch:Partial<AppSettings>)=>void}){
 const t = useT();
 const [result,setResult]=React.useState<Record<string,unknown>|null>(null),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false);
 const act=async(fn:()=>Promise<Record<string,unknown>>)=>{setBusy(true);setError('');try{setResult(await fn());}catch(error){setError(String(error));}finally{setBusy(false);}};
 if(!desktop())return <p>{t('本机订阅客户端仅支持桌面版。')}</p>;
 return <section style={{marginTop:28,paddingTop:22,borderTop:'1px solid var(--border)'}}><h3>{t('本机订阅客户端')}</h3><p className="hint">{t('由官方客户端管理登录和订阅。应用只保存程序路径及任务引用，不收集登录凭据。API Key 与订阅是独立来源。')}</p><label className="team-field"><span>{t('Codex 原生程序')}</span><input value={settings.clients?.codexBin??''} placeholder={t('官方 codex 可执行文件的绝对路径')} onChange={e=>onChange({clients:{...settings.clients,codexBin:e.target.value}})}/></label><div className="team-actions"><button className="btn" onClick={()=>void desktop()!.pickClientBinary().then(path=>{if(path)onChange({clients:{...settings.clients,codexBin:path}});})}>{t('选择 Codex 程序')}</button><button className="btn" disabled={busy} onClick={()=>void act(()=>desktop()!.clientCheck('codex'))}>{t('检查连接与额度')}</button><button className="btn" disabled={busy} onClick={()=>void act(()=>desktop()!.clientLogin())}>{t('官方 ChatGPT 登录')}</button></div><label className="team-field" style={{marginTop:22}}><span>{t('Claude Code 原生程序')}</span><input value={settings.tools.claudeBin} placeholder={t('官方 claude 可执行文件；留空自动查找')} onChange={e=>onChange({tools:{...settings.tools,claudeBin:e.target.value}})}/></label><div className="team-actions"><button className="btn" onClick={()=>void desktop()!.pickClientBinary().then(path=>{if(path)onChange({tools:{...settings.tools,claudeBin:path}});})}>{t('选择 Claude 程序')}</button><button className="btn" disabled={busy} onClick={()=>void act(()=>desktop()!.clientCheck('claude'))}>{t('检查本机程序')}</button></div><p className="hint">{t('Claude Code 请先在官方客户端登录；当前接入保留其权限限制，未获准的操作会暂停处理。订阅客户端可能不提供精确用量，预算会保守占用预留额度。')}</p>{error&&<p role="alert">{error}</p>}{result&&<pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',maxHeight:300,overflow:'auto',fontSize:12}}>{JSON.stringify(result,null,2)}</pre>}</section>;
}
