import { localizeRoles } from '../../lib/role-locale';
import { useT, useLocale } from '../../lib/i18n';
import React from 'react';
import type { AppSettings } from '../../types';
import type { TeamProject } from '../../lib/collaboration';
import { addRole, installModule, type AgentRole } from '../../lib/office';
import { assembleDepartment, departmentTemplates, filterRoles, importDepartmentModules, libraryRoles, parseRoleMarkdown, saveDepartment } from '../../lib/office-library';
import { AGENCY_SOURCE, applySourceChanges, checkRoleSource, type SourcePreview } from '../../lib/role-source';
import AgentAvatar from '../AgentAvatar';

export default function OfficeLibrary({project,settings,onSettings,activeId,selectedRoleId,onRole,onSelected,onDrag,act,onNotice,onError}:{project:TeamProject;settings:AppSettings;onSettings?:(fn:(s:AppSettings)=>AppSettings)=>void;activeId?:string;selectedRoleId?:string;onRole:(id:string)=>void;onSelected:(id:string)=>void;onDrag:(event:React.DragEvent,role:AgentRole)=>void;act:(fn:(p:TeamProject)=>void,success?:string)=>void;onNotice:(text:string)=>void;onError:(text:string)=>void}){
  const tx=useT(),locale=useLocale();
  const library=settings.officeLibrary??{};const roles=localizeRoles(libraryRoles(library,project.office?.customRoles),locale);
  const [tab,setTab]=React.useState<'roles'|'departments'>('roles');const [query,setQuery]=React.useState('');const [category,setCategory]=React.useState('');const [selected,setSelected]=React.useState<string[]>([]);const [page,setPage]=React.useState(0);
  const [imports,setImports]=React.useState<AgentRole[]>([]);const [importErrors,setImportErrors]=React.useState<string[]>([]);const [sourcePreview,setSourcePreview]=React.useState<SourcePreview>();const [sourceSelected,setSourceSelected]=React.useState<string[]>([]);const [busy,setBusy]=React.useState(false);const [progress,setProgress]=React.useState('');const control=React.useRef<AbortController|null>(null);
  React.useEffect(()=>()=>control.current?.abort(),[]);
  const brain={profileId:settings.activeKeyProfileId??settings.keyProfiles[0]?.id??'',model:settings.defaultConfig.model};
  const filtered=filterRoles(roles,query,category);const pages=Math.max(1,Math.ceil(filtered.length/30));const currentPage=Math.min(page,pages-1);const shown=filtered.slice(currentPage*30,currentPage*30+30);
  const categories=[...new Set(roles.map(r=>r.division))].sort((a,b)=>a.localeCompare(b,'zh'));
  const save=(fn:(s:AppSettings)=>AppSettings)=>{try{if(!onSettings)throw Error(tx("当前界面不能保存角色库，请重新打开办公室"));const next=fn(settings).officeLibrary;onSettings(s=>({...s,officeLibrary:next}));return true;}catch(error){onError(String(error));return false;}};
  const addMany=(ids:string[])=>{if(!activeId)return;const chosen=roles.filter(r=>ids.includes(r.id));act(p=>{for(const r of chosen)addRole(p,activeId,r,brain);},tx("已将 {p0} 位独立成员加入部门；尚未启动任务",{p0:chosen.length}));setSelected([]);};
  async function readRoles(files:File[]){setImportErrors([]);setImports([]);if(files.length>100){onError(tx("一次最多导入 100 个 Markdown 文件"));return;}const good:AgentRole[]=[],bad:string[]=[];for(const file of files){try{if(file.size>200000)throw Error(tx("{p0}：超过 200 KB",{p0:file.name}));const role=parseRoleMarkdown(await file.text(),file.name);if([...roles,...good].some(r=>r.name===role.name&&r.instructions===role.instructions))bad.push(tx("{p0}：已存在相同角色，已跳过",{p0:file.name}));else good.push(role);}catch(e){bad.push(String(e));}}setImports(good);setImportErrors(bad);}
  async function check(){if(control.current)return;const controller=new AbortController();control.current=controller;setBusy(true);setSourcePreview(undefined);setProgress(tx("正在检查 GitHub 来源"));try{const preview=await checkRoleSource(library,{signal:controller.signal,onProgress:(done,total)=>setProgress(tx("读取角色 {p0} / {p1}",{p0:done,p1:total}))});setSourcePreview(preview);setSourceSelected(preview.changes.map(c=>c.id));save(s=>({...s,officeLibrary:{...s.officeLibrary,sourceCheckedAt:preview.checkedAt,sourceRevision:preview.revision}}));setProgress(preview.changes.length?tx("找到 {p0} 项变化，等待你选择采用",{p0:preview.changes.length}):tx("已是来源最新目录"));}catch(e){setProgress('');onError(controller.signal.aborted?tx("已取消来源检查，原有目录保留"):String(e));}finally{control.current=null;setBusy(false);}}
  const matches=(text:string)=>query.trim().toLocaleLowerCase().split(/\s+/).every(t=>text.toLocaleLowerCase().includes(t));
  const templates=departmentTemplates(roles).filter(t=>matches(`${t.name} ${tx(t.name)} ${tx(t.category)} ${tx(t.purpose)}`)&&(!category||t.category===category));
  const personal=(library.departments??[]).filter(m=>matches(m.name)&&(!category||category==="我的部门"));
  const local=(project.office?.modules??[]).filter(m=>matches(m.name)&&(!category||category==="当前项目"));
  return <aside className="office-shelf office-library">
    <div className="office-library-tabs" aria-label={tx("模板库")}><button type="button" className="btn" aria-pressed={tab==='roles'} onClick={()=>{setTab('roles');setQuery('');setCategory('');setPage(0);}}>{tx("角色库")}</button><button type="button" className="btn" aria-pressed={tab==='departments'} onClick={()=>{setTab('departments');setQuery('');setCategory('');}}>{tx("部门库")}</button></div>
    <label className="team-field"><span>{tab==='roles'?tx("查找角色"):tx("查找部门")}</span><input aria-label={tab==='roles'?tx("查找角色"):tx("查找部门")} placeholder={tab==='roles'?tx("名称、职责或关键词"):tx("部门名称或用途")} value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label>
    <label className="team-field"><span>{tx("分类")}</span><select aria-label={tx("库分类")} value={category} onChange={e=>{setCategory(e.target.value);setPage(0);}}><option value="">{tx("全部分类")}</option>{(tab==='roles'?categories:["常用组合","按专业组建","我的部门","当前项目"]).map(c=><option key={c} value={c}>{tx(c)}</option>)}</select></label>
    {tab==='roles'?<>
      <p className="hint">{filtered.length} / {roles.length} {tx("个角色 · 加入：")}{project.office?.departments.find(d=>d.id===activeId)?.name??tx("请先选择部门")}</p>
      <div className="office-batch-actions"><label className="team-check"><input type="checkbox" aria-label={tx("选择全部筛选结果")} checked={filtered.length>0&&filtered.every(r=>selected.includes(r.id))} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...filtered.map(r=>r.id)])]:selected.filter(id=>!filtered.some(r=>r.id===id)))}/>{tx("选择筛选结果")}</label><button type="button" className="btn sm" disabled={!selected.length} onClick={()=>setSelected([])}>{tx("清空选择")}</button><button type="button" className="btn sm" disabled={!activeId||!selected.length} onClick={()=>addMany(selected)}>{tx("批量加入（{count}）",{count:selected.length})}</button></div>
      <div className="office-role-list">{shown.map(r=><div className="office-role-tile" key={r.id} draggable onDragStart={e=>onDrag(e,r)}><input type="checkbox" aria-label={tx("选择角色 {p0}",{p0:r.name})} checked={selected.includes(r.id)} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(id=>id!==r.id))}/><button type="button" className="office-role-option" aria-pressed={selectedRoleId===r.id} onClick={()=>onRole(r.id)}><AgentAvatar name={r.name} color={r.color} seed={r.id}/><span><strong>{r.name}</strong><small>{tx(r.division)}</small></span></button><button type="button" className="btn sm" aria-label={tx("加入{p0}",{p0:r.name})} disabled={!activeId} onClick={()=>addMany([r.id])}>{tx("加入")}</button></div>)}</div>
      {!filtered.length&&<p>{tx("没有匹配的角色，试试其他关键词或分类。")}</p>}
      <nav className="office-library-pages" aria-label={tx("角色目录分页")}><button type="button" className="btn sm" disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}>{tx("上一页")}</button><span>{currentPage+1} / {pages}</span><button type="button" className="btn sm" disabled={currentPage+1>=pages} onClick={()=>setPage(currentPage+1)}>{tx("下一页")}</button></nav>
      <label className="btn office-file-input">{tx("批量导入角色")}<input aria-label={tx("批量导入角色 Markdown")} type="file" accept=".md,text/markdown" multiple onChange={e=>{void readRoles(Array.from(e.target.files??[]));e.target.value='';}}/></label>
      {!!imports.length&&<section className="office-import-preview"><h4>{tx("待导入")}{imports.length} {tx("个角色")}</h4><ul>{imports.map(r=><li key={r.id}>{r.name}</li>)}</ul><button type="button" className="btn sm" onClick={()=>{const imported=imports;save(s=>({...s,officeLibrary:{...s.officeLibrary,roles:[...(s.officeLibrary?.roles??[]),...imported]}}));setImports([]);onNotice(tx("已导入 {p0} 个角色，所有项目均可使用",{p0:imported.length}));}}>{tx("保存到角色库")}</button><button type="button" className="btn sm ghost" onClick={()=>setImports([])}>{tx("取消")}</button></section>}
      {!!importErrors.length&&<details open><summary>{tx("导入提示 ·")}{importErrors.length}</summary>{importErrors.map((e,i)=><p key={i}>{e}</p>)}</details>}
      <details className="office-source"><summary>{tx("角色来源与更新")}</summary><p>{tx("agency-agents · 内置")}{AGENCY_SOURCE.roleCount} {tx("个角色。更新先审阅，已有成员和部门快照保持独立。")}</p><a href={`https://github.com/${AGENCY_SOURCE.repo}/tree/${library.sourceRevision??AGENCY_SOURCE.revision}`} target="_blank" rel="noreferrer">{tx("查看来源版本")}</a>{library.sourceCheckedAt&&<p>{tx("上次检查：")}{new Date(library.sourceCheckedAt).toLocaleString()}</p>}<button type="button" className="btn sm" disabled={busy} onClick={()=>void check()}>{tx("检查来源更新")}</button>{busy&&<button type="button" className="btn sm" onClick={()=>control.current?.abort()}>{tx("取消检查")}</button>}<p role="status">{progress}</p>
        {sourcePreview&&sourcePreview.changes.length>0&&<><div className="office-batch-actions"><button type="button" className="btn sm" onClick={()=>setSourceSelected(sourcePreview.changes.map(c=>c.id))}>{tx("全选变化")}</button><button type="button" className="btn sm" onClick={()=>setSourceSelected([])}>{tx("清空变化选择")}</button></div><div className="office-source-changes">{sourcePreview.changes.map(c=><div key={c.id}><label className="team-check"><input type="checkbox" checked={sourceSelected.includes(c.id)} onChange={e=>setSourceSelected(e.target.checked?[...sourceSelected,c.id]:sourceSelected.filter(id=>id!==c.id))}/>{({added:tx("新增"),updated:tx("更新"),removed:tx("来源移除")})[c.kind]} · {(c.after??c.before)?.name}</label><details><summary>{tx("查看职责变化")}</summary>{c.before&&<><strong>{tx("当前模板")}</strong><pre>{c.before.instructions}</pre></>}{c.after&&<><strong>{tx("来源版本")}</strong><pre>{c.after.instructions}</pre></>}</details></div>)}</div><p>{tx("移除仅影响模板目录，已组装成员和个人部门仍保留。")}</p><button type="button" className="btn sm" disabled={!sourceSelected.length} onClick={()=>{save(s=>({...s,officeLibrary:applySourceChanges(s.officeLibrary??{},sourcePreview,sourceSelected)}));onNotice(tx("已采用 {p0} 项来源变化",{p0:sourceSelected.length}));setSourcePreview(undefined);setProgress(tx("来源变化已采用"));}}>{tx("采用选中的变化（{count}）",{count:sourceSelected.length})}</button></>}
      </details>
    </>:<>
      <p className="hint">{tx("内置组合和你的部门可跨项目复用。先组装，再配置工作流与启动任务。")}</p><div className="office-department-library">
      {templates.map(t=><details key={t.id}><summary>{tx(t.name)}<small>{t.groups.length} {tx("个部门 ·")}{t.groups.reduce((n,g)=>n+g.roleIds.length,0)} {tx("位成员")}</small></summary><p>{tx(t.purpose)}</p><ul>{t.groups.map((g,i)=><li key={i}>{tx(g.name)}：{g.roleIds.map(id=>roles.find(r=>r.id===id)?.name).join('、')}</li>)}</ul><button type="button" className="btn sm" onClick={()=>act(p=>{onSelected(assembleDepartment(p,{...t,name:tx(t.name),purpose:tx(t.purpose),groups:t.groups.map(g=>({...g,name:tx(g.name),purpose:tx(g.purpose)}))},roles,brain));},tx("已组装{p0}，尚未启动任务",{p0:tx(t.name)}))}>{tx("组装")}{tx(t.name)}</button></details>)}
      {personal.map(m=><details key={m.id}><summary>{m.name}<small>{tx("我的部门 ·")}{m.departments.length} {tx("个部门 ·")}{m.members.length} {tx("位成员")}</small></summary><p>{m.members.map(member=>member.name).join('、')}</p><p>{tx("从库中组装后，需要为新成员配置模型与工具。")}</p><button type="button" className="btn sm" onClick={()=>act(p=>onSelected(installModule(p,m,undefined,true)),tx("已组装{p0}，请配置新成员的模型与工具",{p0:m.name}))}>{tx("组装")}{m.name}</button><button type="button" className="btn sm ghost" onClick={()=>{save(s=>({...s,officeLibrary:{...s.officeLibrary,departments:(s.officeLibrary?.departments??[]).filter(d=>d.id!==m.id)}}));onNotice(tx("已从个人部门库移除，项目中的已组装部门保留"));}}>{tx("移出部门库")}</button></details>)}
      {local.map(m=><details key={m.id}><summary>{m.name}<small>{tx("当前项目模块 ·")}{m.members.length} {tx("位成员")}</small></summary><button type="button" className="btn sm" onClick={()=>{save(s=>({...s,officeLibrary:saveDepartment(s.officeLibrary??{},m)}));onNotice(tx("已保存到跨项目部门库"));}}>{tx("保存到我的部门库")}</button><button type="button" className="btn sm" onClick={()=>act(p=>onSelected(installModule(p,m)),tx("已组装独立部门"))}>{tx("在当前项目组装")}</button></details>)}
      {!templates.length&&!personal.length&&!local.length&&<p>{tx("没有匹配的部门。可在部门的“整理”中保存自己的组合。")}</p>}</div>
      <label className="btn office-file-input">{tx("批量导入部门模块")}<input aria-label={tx("批量导入部门模块")} type="file" accept=".json,application/json" multiple onChange={e=>{const files=Array.from(e.target.files??[]);e.target.value='';void (async()=>{try{if(files.length>30||files.some(f=>f.size>2000000))throw Error(tx("一次最多 30 个模块，每个不超过 2 MB"));const modules=importDepartmentModules(await Promise.all(files.map(async f=>({name:f.name,text:await f.text()}))));save(s=>{let next=s.officeLibrary??{};for(const m of modules)next=saveDepartment(next,m);return {...s,officeLibrary:next};});onNotice(tx("已导入 {p0} 组部门到个人部门库，尚未组装",{p0:modules.length}));}catch(err){onError(String(err));}})();}}/></label>
    </>}
  </aside>;
}
