import WorkspacePlanCard from './WorkspacePlanCard';
import { workspaceContext, workspaceStamp, prepareWorkspacePlan, workspacePlannerInstructions } from '../../lib/workspace-planner';
import { desktop } from '../../lib/transport';
import { localizeRoles } from '../../lib/role-locale';
import { useT, useLocale } from '../../lib/i18n';
import { libraryRoles } from '../../lib/office-library';
import ButlerPreferences from './ButlerPreferences';
import ProjectMemoryPanel from '../ProjectMemoryPanel';
import { addMemory, redactSecrets, type ProjectMemoryItem } from '../../lib/memory-core';
import { loadSkills, makeSkill, saveSkills, type Skill } from '../../lib/skills';
import { butlerContext, validLearning } from '../../lib/butler';
import React from 'react';
import type { AppSettings } from '../../types';
import type { TeamProject } from '../../lib/collaboration';
import { uid, secretGet } from '../../lib/store';
import { AGENT_ROLES, ensureOffice, officeOf, type PlanningTurn } from '../../lib/office';
import { plannerSystem, parsePlannerReply, repairPlannerReply, plannerMessage, PlannerDraftError, plannerRoutes, wantsDiscussion, adoptProposal } from '../../lib/office-planner';
import { requestAssistant, type AssistantRetry } from '../../lib/assistant-request';
import { limitKey, mergeLearnedLimit } from '../../lib/limits';
import { probeCompatibility } from '../../lib/compatibility-probe';
import Markdown from '../Markdown';
export default function OfficePlanner({project,settings,update,onTask,onSettings,onSettingsChange,memoryItems=[],onMemory,onLaunch}:{project:TeamProject;settings:AppSettings;update:(fn:(p:TeamProject)=>void)=>Promise<unknown>;onTask:(id:string)=>void;onLaunch?:(taskId:string)=>void;onSettings:()=>void;onSettingsChange?:(fn:(s:AppSettings)=>AppSettings)=>void;memoryItems?:ProjectMemoryItem[];onMemory?:(fn:(items:ProjectMemoryItem[])=>ProjectMemoryItem[])=>void}){
  const tx=useT(),locale=useLocale();
  const [skills,setSkills]=React.useState<Skill[]>([]);React.useEffect(()=>{void loadSkills().then(setSkills).catch(()=>{});},[]);
  const roles=localizeRoles(libraryRoles(settings.officeLibrary,project.office?.customRoles),locale);
  const office=officeOf(project),[draft,setDraft]=React.useState(office.draft??''),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
  const [brain,setBrain]=React.useState(office.brain??{profileId:settings.activeKeyProfileId??settings.keyProfiles[0]?.id??'',model:settings.defaultConfig.model});
  const control=React.useRef<AbortController|null>(null),settingsRef=React.useRef(settings);settingsRef.current=settings;const [wait,setWait]=React.useState(0);React.useEffect(()=>{if(office.planning?.some(t=>t.pending))void update(p=>{for(const t of ensureOffice(p).planning??[])if(t.pending){t.pending=false;t.error=tx("上次筹备中断，可继续说明你的想法；已有记录保留。");}}).catch(()=>{});return()=>control.current?.abort();},[]);
  const profile=settings.keyProfiles.find(p=>p.id===brain.profileId),history=office.planning??[],routes=plannerRoutes(settings,project,brain);
  async function send(text:string,repairTarget?:PlanningTurn){
    if(control.current||!text.trim())return;if(!profile||!brain.model){setError(tx("先为协作设计助手选择一个已配置的模型。"));return;}
    const baseStamp=workspaceStamp(project),environment={settings,roles,skills};const controller=new AbortController();control.current=controller;setBusy(true);setError('');setDraft('');
    const user:PlanningTurn={id:uid('plan'),role:'user',text:text.trim()},answer:PlanningTurn={id:uid('plan'),role:'assistant',text:'',pending:true,sourceTurnId:repairTarget?.sourceTurnId??repairTarget?.id};
    let raw='';
    try {
      await update(p=>{const o=ensureOffice(p);o.brain=brain;o.draft='';o.planning=[...(o.planning??[]),user,answer];});
      const key=await secretGet(profile.id);if(!key)throw Error(tx("此接入尚未保存 API Key，请到设置中填写。"));
      const compatibility=await probeCompatibility(profile,brain.model,key,{signal:controller.signal});if(compatibility.status!=='ready')throw Error(compatibility.note);
      const cfg={...settings.defaultConfig,model:brain.model,client:undefined,effortLevel:'off' as const,thinkingStyle:'auto' as const,stream:true,params:{...settings.defaultConfig.params,max_tokens:{enabled:true,value:16384},max_completion_tokens:{enabled:false,value:4096}}};
      const completedRuns=project.runs.filter(r=>['completed','failed','cancelled'].includes(r.status)).slice(-5).map(r=>({id:r.id,goal:r.goal,status:r.status,results:r.attempts.map(a=>({output:redactSecrets(a.output).text.slice(-4000),error:a.error}))}));
      const planningHistory=repairTarget?history.slice(0,history.findIndex(t=>t.id===repairTarget.id)+1):history;
      const workspace={...workspaceContext(project,environment),meetings:await desktop()?.meetingState(project.id).catch(()=>[])};
      const context={workspace,repairTarget:repairTarget?{turnId:repairTarget.id,originalReply:repairTarget.rawReply??repairTarget.text,instruction:'修复这条指定回复，以此前的用户需求为准，不要误改其他方案。'}:undefined,modelRoutes:routes.slice(0,100),completedRuns,existingDepartments:office.departments.map(d=>({name:d.name,purpose:d.purpose,members:d.memberIds.map(id=>project.members.find(m=>m.id===id)?.name)})),conversation:[...planningHistory.filter(t=>!t.pending).map(t=>({role:t.role,text:t.text,proposal:t.proposal,workspacePlan:t.workspacePlan,workspaceResult:t.workspaceResult,questions:t.questions,learning:t.learning,learningDecisions:t.learningDecisions,rawReply:t.rawReply})),{role:'user',text:user.text}]};
      const system=plannerSystem(roles)+'\n\n'+workspacePlannerInstructions+'\n返回 JSON 外层为 {message,questions,workspacePlan,learning}。workspacePlan 按输入 workspace.schema；旧 proposal 仅兼容历史，优先用完整安排接口。\nRespond in the user’s language; if unclear, use '+(settings.locale??'zh-Hans')+'.\n\n'+butlerContext(settings,office.instructions??'',memoryItems,skills,text);
      // Same pacing, limit learning and rate-limit wait as the single agent; learned limits are shared through settings.
      const route=limitKey(profile.id,brain.model,profile.baseUrl);
      const retry:AssistantRetry={autoRetry:settings.autoRetry??2,modelInfo:[...(settings.cachedModels[profile.id]??[]),...(settings.customModels?.[profile.id]??[])].find(m=>m.id===brain.model),limitOf:()=>settingsRef.current.modelLimits?.[route],onLearnLimit:l=>onSettingsChange?.(s=>({...s,modelLimits:{...(s.modelLimits??{}),[route]:mergeLearnedLimit(s.modelLimits?.[route],l)}})),onWait:setWait};
      raw=await requestAssistant(profile,cfg,JSON.stringify(context),controller.signal,system,value=>{raw=value;},retry);
      const expectDiscussion=wantsDiscussion(planningHistory.filter(t=>t.role==='user').map(t=>t.text).concat(repairTarget?[]:[text]));
      const reply=await repairPlannerReply(raw,roles,routes,async correction=>{await update(p=>{const t=ensureOffice(p).planning?.find(t=>t.id===answer.id);if(t)t.repairing=true;});return requestAssistant(profile,cfg,JSON.stringify({...context,correction}),controller.signal,system,value=>{raw=value;},retry);},expectDiscussion,plan=>{prepareWorkspacePlan(project,plan,environment);},!!repairTarget||/(?:帮我|请.{0,8}(?:安排|创建|调整|建立|启动|暂停)|我要|我想|build|create|set up|schedule)/i.test(text)&&!/(?:如何|怎样|是什么|how to|what is)/i.test(text));
      const evidence=[...planningHistory.filter(t=>t.role==='user').map(t=>t.text),user.text,JSON.stringify(completedRuns)].join('\n');
      const learning=settings.butler?.learning===false?[]:validLearning(reply.learning,evidence);
      await update(p=>{const t=ensureOffice(p).planning?.find(t=>t.id===answer.id);if(t)Object.assign(t,{text:reply.message,questions:reply.questions,proposal:reply.proposal,workspacePlan:reply.workspacePlan,workspaceStamp:baseStamp,learning,pending:false,repairing:false});});
    }catch(e){const message=controller.signal.aborted?tx("筹备已停止，已有内容保留。"):e instanceof Error?e.message:String(e);setError(message);await update(p=>{const t=ensureOffice(p).planning?.find(t=>t.id===answer.id);if(t)Object.assign(t,{text:plannerMessage(e instanceof PlannerDraftError?e.rawReply:raw)||tx("没有收到完整方案。"),rawReply:e instanceof PlannerDraftError?e.rawReply:raw,pending:false,repairing:false,error:message});}).catch(()=>{});}
    finally{control.current=null;setBusy(false);setWait(0);}
  }
  async function repairTurn(turn:PlanningTurn){
    try{const reply=parsePlannerReply(turn.rawReply??turn.text,roles);if(reply.workspacePlan){prepareWorkspacePlan(project,reply.workspacePlan,{settings,roles,skills});}else if(!reply.proposal||(wantsDiscussion(history.slice(0,history.findIndex(t=>t.id===turn.id)+1).filter(t=>t.role==='user').map(t=>t.text))&&!reply.proposal.discussion))throw Error('Incomplete draft');await update(p=>{const saved=ensureOffice(p).planning?.find(t=>t.id===turn.id);if(saved)Object.assign(saved,{text:reply.message,proposal:reply.proposal,workspacePlan:reply.workspacePlan,workspaceStamp:workspaceStamp(project),questions:reply.questions,error:undefined,pending:false,repairing:false});});setError('');}
    catch{await send(tx('请修复这份未能采用的方案，保留此前已说明的目标与材料，给出可采用的团队、模型分工和流程。'),turn);}
  }
  return <section className="office-planner" aria-label={tx("wickrunAI 管家")}>
    <div className="office-heading"><div><h2>{tx("先说说，你想做成什么？")}</h2><p>{tx("和管家商量目标、了解客户端、调整团队或复盘经验。它拟方案，你来决定。")}</p></div><details><summary>{tx("助手的模型")}</summary><div className="office-brain"><select aria-label={tx("设计助手接入")} value={brain.profileId} onChange={e=>setBrain({profileId:e.target.value,model:settings.cachedModels[e.target.value]?.[0]?.id??''})}>{settings.keyProfiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input aria-label={tx("设计助手模型")} value={brain.model} list="office-planner-models" onChange={e=>setBrain({...brain,model:e.target.value})}/><datalist id="office-planner-models">{(settings.cachedModels[brain.profileId]??[]).map(m=><option key={m.id} value={m.id}/>)}</datalist><button className="btn sm" onClick={onSettings}>{tx("管理接入")}</button></div></details></div>
    <ButlerPreferences settings={settings} onSettings={onSettingsChange} projectRules={office.instructions??''} onProjectRules={text=>{void update(p=>{ensureOffice(p).instructions=text;}).catch(e=>setError(String(e)));}} skills={skills}/>
    {onMemory&&<details className="butler-memory"><summary>{tx("查看、修改管家的项目记忆")}</summary><ProjectMemoryPanel items={memoryItems} onChange={items=>onMemory(()=>items)} detailed/></details>}
    {!history.length&&<div className="office-examples">{[tx("我想做一个自媒体账号，但还没想清楚从哪里开始"),tx("帮我把一个产品想法变成能试用的原型"),tx("我有一套现成流程，想调整其中的分工")].map(text=><button className="btn" key={text} onClick={()=>setDraft(text)}>{text}</button>)}</div>}
    <div className="office-planning-history">{history.map((turn,i)=><article key={turn.id} className={`office-turn ${turn.role}`}>
      <strong>{turn.role==='user'?tx("你"):tx("wickrunAI 管家")}</strong>
      {turn.pending?<p role="status">{wait>0?tx("等待调用额度，{s} 秒后自动继续；可随时停止。",{s:Math.ceil(wait/1000)}):turn.repairing?tx("正在修正方案格式与成员分工…"):tx("正在梳理需求与可行方案…")}</p>:turn.error?<><Markdown text={plannerMessage(turn.text)}/><p role="alert">{turn.error}</p><button className="btn" disabled={busy} onClick={()=>void repairTurn(turn)}>{tx('修复方案')}</button><details><summary>{tx('查看原始回复')}</summary><pre>{turn.rawReply??turn.text}</pre></details></>:<Markdown text={turn.text}/>}
      {turn.questions?.map((q,index)=><div className="office-question" key={index}><p>{q.text}</p><div>{q.options.map(option=><button className="btn sm" disabled={busy} key={option} onClick={()=>setDraft(v=>(v?v+'\n':'')+`${q.text}：${option}`)}>{option}</button>)}</div></div>)}
      {turn.learning?.map((item,index)=><div className="butler-learning" key={index}><strong>{item.kind==='skill'?tx("可复用技能建议"):tx("值得记住的经验 / 偏好")}</strong><p>{item.text}</p><small>{tx("适用：")}{item.applicability}</small><blockquote>{tx("依据：")}{item.sourceQuote}</blockquote>{turn.learningDecisions?.[index]?<small>{turn.learningDecisions[index]==='saved'?tx("已保存，可在记忆或技能管理中调整"):tx("已忽略")}</small>:<div className="team-actions"><button className="btn sm" disabled={!onMemory&&item.kind!=='skill'} onClick={()=>{void (async()=>{if(item.kind==='skill'){const list=await loadSkills(),body=tx("适用：{p0}\n\n{p1}\n\n来源：管家对话 {p2}\n证据：{p3}",{p0:item.applicability,p1:item.text,p2:turn.id,p3:item.sourceQuote});if(!list.some(s=>s.body===body))await saveSkills([...list,makeSkill({name:'butler-'+turn.id.slice(-8)+'-'+index,description:item.applicability,body,enabled:false,source:tx("wickrunAI 管家：用户采用的学习草案")})]);}else onMemory?.(items=>addMemory(items,{text:item.text,kind:item.kind==='preference'?'preference':'lesson',source:'candidate',sourceRef:turn.id,applicability:item.applicability,evidence:item.sourceQuote}).items);await update(p=>{const t=ensureOffice(p).planning!.find(t=>t.id===turn.id)!;(t.learningDecisions??={})[index]='saved';});})().catch(e=>setError(String(e)));}}>{item.kind==='skill'?tx("保存为停用的技能草案"):tx("采用为项目记忆")}</button><button className="btn sm ghost" onClick={()=>{void update(p=>{const t=ensureOffice(p).planning!.find(t=>t.id===turn.id)!;(t.learningDecisions??={})[index]='dismissed';}).catch(e=>setError(String(e)));}}>{tx("忽略")}</button></div>}</div>)}
      {turn.workspacePlan&&<WorkspacePlanCard turn={turn} project={project} environment={{settings,roles,skills}} update={update} onLaunch={onLaunch} onRepair={()=>void send(tx('请根据协作空间当前状态更新这份工作安排，保留目标并修复无法采用的部分。'),turn)}/>}
      {turn.proposal&&<details className="office-proposal" open={i===history.length-1}><summary>{tx("方案草案 ·")}{turn.proposal.title}</summary><p><strong>{tx("会交给你：")}</strong>{turn.proposal.deliverable}</p><p><strong>{tx("怎样判断做好了：")}</strong>{turn.proposal.acceptance}</p>
        {!!turn.proposal.assumptions.length&&<div className="office-assumptions"><strong>{tx("这份方案采用的假设")}</strong><ul>{turn.proposal.assumptions.map(a=><li key={a}>{a}</li>)}</ul></div>}
        <p><strong>{tx("团队分工：")}</strong>{turn.proposal.departments.map(d=>`${d.name}（${d.purpose}）`).join('；')}</p>
        <p>{turn.proposal.mode==='parallel'?tx("这些工作并行开展"):tx("按下面顺序接力")}</p><ol>{turn.proposal.steps.map((s,index)=><li key={index}><strong>{roles.find(r=>r.id===s.roleId)?.name}</strong>：{s.instruction}<small>{tx("交付：")}{s.output}</small></li>)}</ol>
        {turn.proposal.discussion&&<section className="office-discussion-plan"><h4>{tx('讨论安排')}</h4><p>{tx('共同讨论 {rounds} 轮，每轮阅读前文并回应其他成员。',{rounds:turn.proposal.discussion.rounds})}</p><p>{turn.proposal.discussion.focus}</p><p>{tx('讨论产出：{output}',{output:turn.proposal.discussion.output})}</p><p>{tx('整理结论：{name}',{name:roles.find(r=>r.id===turn.proposal!.discussion!.synthesisRoleId)?.name??''})}</p></section>}
        <p>{turn.proposal.reviewRoleId?tx("独立复核后，交给你验收"):tx("交给你验收（本方案未配置独立质检）")}</p>
        {turn.proposal.reviewRoleId&&<p>{tx('复核由独立成员承担；即使用同一角色模板，也不会复核自己执行的工作。')}</p>}
        <details className="office-plan-models" open><summary>{tx('各角色使用的模型')}</summary><p className="hint">{tx('采用前可直接调整模型。多角色可以共用模型；只有选择不同模型，才是多模型讨论。')}</p>{[...new Set(turn.proposal.departments.flatMap(d=>d.roleIds))].map(id=>{const a=turn.proposal!.modelAssignments?.find(a=>a.roleId===id)??brain;const key=JSON.stringify([a.profileId,a.model]);return <label className="team-field" key={id}><span>{roles.find(r=>r.id===id)?.name??id}</span><select aria-label={tx('角色模型：{name}',{name:roles.find(r=>r.id===id)?.name??id})} value={key} disabled={busy||!!turn.adoptedTaskId} onChange={e=>{const [profileId,model]=JSON.parse(e.target.value);void update(p=>{const target=ensureOffice(p).planning?.find(t=>t.id===turn.id);if(target?.proposal)target.proposal.modelAssignments=[...(target.proposal.modelAssignments??[]).filter(a=>a.roleId!==id),{roleId:id,profileId,model}];}).catch(e=>setError(String(e)));}}>{!routes.some(r=>JSON.stringify([r.profileId,r.model])===key)&&<option value={key}>{tx('请选择可用模型')}</option>}{routes.map(r=><option key={JSON.stringify([r.profileId,r.model])} value={JSON.stringify([r.profileId,r.model])}>{r.label}</option>)}</select></label>;})}</details>
        <div className="team-actions">{turn.adoptedTaskId?<button className="btn" onClick={()=>onTask(turn.adoptedTaskId!)}>{tx("打开已准备的任务")}</button>:<button className="btn primary" disabled={busy||!!turn.questions?.length} onClick={()=>{setError('');void update(p=>{adoptProposal(p,turn,brain,roles,routes);}).catch(e=>setError(String(e)));}}>{tx("采用方案，建立团队和任务草案")}</button>}<button className="btn" disabled={busy} onClick={()=>setDraft(tx("关于“{p0}”，我想调整：",{p0:turn.proposal!.title}))}>{tx("继续商量")}</button></div><small>{tx("采用会建立独立团队、讨论管线和任务草案，保留你的原始需求与材料；不会启动执行。之后在任务页检查并开始。讨论不替代独立质检；文件操作和外部发布仍需配置相应能力。")}</small>
      </details>}
    </article>)}</div>
    <form onSubmit={e=>{e.preventDefault();void send(draft);}}><textarea aria-label={tx("告诉协作设计助手你的想法")} placeholder={tx("例如：我想每周做两条短视频，面向刚开始健身的人。先帮我想想怎样开始。")} rows={3} value={draft} onChange={e=>{const value=e.target.value;setDraft(value);void update(p=>{ensureOffice(p).draft=value;}).catch(()=>{});}}/><div className="team-actions"><small>{tx("先筹备，后启动。也可以直接说出对方案的修改意见。")}</small>{busy?<button type="button" className="btn" onClick={()=>control.current?.abort()}>{tx("停止筹备")}</button>:<button className="btn primary" disabled={!draft.trim()}>{tx("一起想清楚")}</button>}</div></form>
    {error&&<p role="alert" className="team-error">{error}</p>}
  </section>;
}
